# Generated by Django 4.1 on 2022-08-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile-pics/default.jpg', upload_to='profile-pics'),
        ),
    ]
